# Generated by Django 6.0 on 2025-12-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(default='About', max_length=50, verbose_name='Badge')),
                ('title', models.CharField(default='Experience You Can Trust', max_length=200, verbose_name='Sarlavha')),
                ('content_1', models.TextField(verbose_name='Paragraf 1')),
                ('content_2', models.TextField(blank=True, verbose_name='Paragraf 2')),
                ('content_3', models.TextField(blank=True, verbose_name='Paragraf 3')),
                ('stat_exp_val', models.CharField(default='20+', max_length=20, verbose_name='Tajriba (Yil)')),
                ('stat_exp_label', models.CharField(default='Years of Experience', max_length=50, verbose_name='Label')),
                ('stat_cases_val', models.CharField(default='500+', max_length=20, verbose_name='Ishlar Soni')),
                ('stat_cases_label', models.CharField(default='Cases Won', max_length=50, verbose_name='Label')),
                ('stat_clients_val', models.CharField(default='300+', max_length=20, verbose_name='Mijozlar')),
                ('stat_clients_label', models.CharField(default='Satisfied Clients', max_length=50, verbose_name='Label')),
                ('stat_awards_val', models.CharField(default='15+', max_length=20, verbose_name='Mukofotlar')),
                ('stat_awards_label', models.CharField(default='Legal Awards', max_length=50, verbose_name='Label')),
            ],
            options={
                'verbose_name': '2. About Section',
                'verbose_name_plural': '2. About Section',
            },
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Corporate M&A', max_length=50, verbose_name='Kategoriya')),
                ('year', models.CharField(default='2024', max_length=10, verbose_name='Yil')),
                ('title', models.CharField(max_length=200, verbose_name='Ish Nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('outcome', models.CharField(default='$250M Deal Closed', max_length=200, verbose_name='Natija ($)')),
            ],
            options={
                'verbose_name': '4. Case Study',
                'verbose_name_plural': '4. Case Studies',
            },
        ),
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(default='Contact', max_length=50)),
                ('title', models.CharField(default='Schedule a Consultation', max_length=100)),
                ('subtitle', models.CharField(default='Get in touch...', max_length=255)),
                ('phone_number', models.CharField(default='+998 (90) 123-45-67', max_length=50, verbose_name="Telefon (Ko'rinishi)")),
                ('phone_link', models.CharField(default='tel:+998901234567', max_length=50, verbose_name='Telefon (Link)')),
                ('email', models.EmailField(default='info@yurist.uz', max_length=254)),
                ('telegram_username', models.CharField(default='@shohjahon_yurist', max_length=50, verbose_name='Telegram User')),
                ('telegram_link', models.URLField(default='https://t.me/yurist')),
                ('address', models.CharField(default='Toshkent shahar, Yunusobod...', max_length=255, verbose_name='Manzil')),
                ('map_url', models.TextField(blank=True, verbose_name='Google Maps Embed URL (Iframe src)')),
                ('work_days_label', models.CharField(default='Dushanba - Juma', max_length=50)),
                ('work_days_hours', models.CharField(default='09:00 - 18:00', max_length=50)),
                ('saturday_label', models.CharField(default='Shanba', max_length=50)),
                ('saturday_hours', models.CharField(default='10:00 - 14:00', max_length=50)),
                ('sunday_label', models.CharField(default='Yakshanba', max_length=50)),
                ('sunday_hours', models.CharField(default='Yopiq', max_length=50)),
            ],
            options={
                'verbose_name': '6. Kontakt va Futer',
                'verbose_name_plural': '6. Kontakt va Futer',
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='20+ Years of Legal Excellence', max_length=100, verbose_name='Badge Text')),
                ('main_title', models.CharField(default='Defending Your Rights with Expertise', max_length=255, verbose_name='Katta Sarlavha')),
                ('description', models.TextField(default='Providing trusted legal counsel...', verbose_name='Izoh')),
                ('button_text', models.CharField(default='Learn More', max_length=50, verbose_name='Tugma Matni')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Hero Rasmi')),
                ('trust_1_label', models.CharField(default='Bar Association', max_length=50, verbose_name='Trust 1 - Sarlavha')),
                ('trust_1_sub', models.CharField(default='Member Since 2003', max_length=50, verbose_name='Trust 1 - Izoh')),
                ('trust_2_label', models.CharField(default='500+ Cases', max_length=50, verbose_name='Trust 2 - Sarlavha')),
                ('trust_2_sub', models.CharField(default='Successfully Won', max_length=50, verbose_name='Trust 2 - Izoh')),
                ('trust_3_label', models.CharField(default='98% Success', max_length=50, verbose_name='Trust 3 - Sarlavha')),
                ('trust_3_sub', models.CharField(default='Rate', max_length=50, verbose_name='Trust 3 - Izoh')),
            ],
            options={
                'verbose_name': '1. Hero Section',
                'verbose_name_plural': '1. Hero Section',
            },
        ),
        migrations.CreateModel(
            name='PracticeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_name', models.CharField(help_text='Masalan: scale, shield, building-2', max_length=50, verbose_name='Ikonka nomi (Lucide)')),
                ('title', models.CharField(max_length=100, verbose_name='Xizmat Nomi')),
                ('description', models.TextField(verbose_name='Izoh')),
                ('tags', models.CharField(help_text='Biznes, Sud, Mulk', max_length=200, verbose_name='Taglar (Vergul bilan)')),
            ],
            options={
                'verbose_name': '3. Xizmat',
                'verbose_name_plural': '3. Xizmatlar',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(verbose_name='Fikr')),
                ('author_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('author_role', models.CharField(max_length=100, verbose_name='Lavozim')),
                ('initials', models.CharField(max_length=5, verbose_name='Bosh harflar')),
            ],
            options={
                'verbose_name': '5. Fikr (Testimonial)',
                'verbose_name_plural': '5. Testimonials',
            },
        ),
    ]
