# Generated by Django 6.0 on 2025-12-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutsection',
            options={},
        ),
        migrations.AlterModelOptions(
            name='casestudy',
            options={},
        ),
        migrations.AlterModelOptions(
            name='contactsettings',
            options={},
        ),
        migrations.AlterModelOptions(
            name='herosection',
            options={},
        ),
        migrations.AlterModelOptions(
            name='practicearea',
            options={},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={},
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='content_1',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='content_2',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='content_3',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='stat_awards_label',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='stat_awards_val',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='stat_cases_label',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='stat_cases_val',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='stat_clients_label',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='stat_clients_val',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='stat_exp_label',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='stat_exp_val',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='phone_link',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='saturday_label',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='sunday_label',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='telegram_link',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='telegram_username',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='work_days_hours',
        ),
        migrations.RemoveField(
            model_name='contactsettings',
            name='work_days_label',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='badge_text',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='main_title',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='trust_1_label',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='trust_1_sub',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='trust_2_label',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='trust_2_sub',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='trust_3_label',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='trust_3_sub',
        ),
        migrations.RemoveField(
            model_name='practicearea',
            name='icon_name',
        ),
        migrations.RemoveField(
            model_name='practicearea',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='author_role',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='initials',
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='awards_label',
            field=models.CharField(default='Mukofotlar', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='awards_value',
            field=models.CharField(default='25+', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='cases_label',
            field=models.CharField(default='Yutuqli Ishlar', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='cases_value',
            field=models.CharField(default='1000+', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='clients_label',
            field=models.CharField(default='Mamnun Mijozlar', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='clients_value',
            field=models.CharField(default='500+', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='content',
            field=models.TextField(default='', help_text='Paragraflarni yangi qator bilan ajrating'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='experience_label',
            field=models.CharField(default='Yillik Tajriba', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='experience_value',
            field=models.CharField(default='15+', max_length=50),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='saturday_text',
            field=models.CharField(default='Shanba', max_length=100),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='sunday_text',
            field=models.CharField(default='Yakshanba', max_length=100),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='work_days',
            field=models.CharField(default='Dushanba - Juma', max_length=100),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='work_hours',
            field=models.CharField(default='09:00 - 18:00', max_length=100),
        ),
        migrations.AddField(
            model_name='herosection',
            name='badge',
            field=models.CharField(default='YURIDIK XIZMATLAR', max_length=100),
        ),
        migrations.AddField(
            model_name='herosection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='stat_1_label',
            field=models.CharField(default='Tajriba', max_length=50),
        ),
        migrations.AddField(
            model_name='herosection',
            name='stat_1_sublabel',
            field=models.CharField(default='15 Yil', max_length=50),
        ),
        migrations.AddField(
            model_name='herosection',
            name='stat_2_label',
            field=models.CharField(default='Mijozlar', max_length=50),
        ),
        migrations.AddField(
            model_name='herosection',
            name='stat_2_sublabel',
            field=models.CharField(default='500+', max_length=50),
        ),
        migrations.AddField(
            model_name='herosection',
            name='stat_3_label',
            field=models.CharField(default='Yutuqlar', max_length=50),
        ),
        migrations.AddField(
            model_name='herosection',
            name='stat_3_sublabel',
            field=models.CharField(default='98%', max_length=50),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title',
            field=models.CharField(default='Professional Yuridik Yordam', max_length=200),
        ),
        migrations.AddField(
            model_name='practicearea',
            name='icon',
            field=models.CharField(default='Briefcase', help_text='Lucide icon nomi (masalan: Shield, Scale)', max_length=50),
        ),
        migrations.AddField(
            model_name='practicearea',
            name='specialties',
            field=models.TextField(blank=True, help_text='Mutaxassisliklarni vergul bilan ajratib yozing'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author',
            field=models.CharField(default='Hi', max_length=100, verbose_name='Mijoz ismi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='role',
            field=models.CharField(default='Mijoz', max_length=100, verbose_name='Lavozimi/Kompaniyasi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='badge',
            field=models.CharField(default='BIZ HAQIMIZDA', max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='title',
            field=models.CharField(default='Tajribali Advokatlar Jamoasi', max_length=200),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='category',
            field=models.CharField(default='Yuridik Himoya', max_length=100),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='outcome',
            field=models.CharField(help_text='Natija (masalan: $2M Undirildi)', max_length=200),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='year',
            field=models.CharField(default='2024', max_length=4),
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='badge',
            field=models.CharField(default='ALOQA', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='map_url',
            field=models.TextField(help_text='Google Maps Embed URL'),
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='saturday_hours',
            field=models.CharField(default='10:00 - 14:00', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='subtitle',
            field=models.CharField(default='Sizga yordam berishga tayyormiz', max_length=200),
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='sunday_hours',
            field=models.CharField(default='Yopiq', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='title',
            field=models.CharField(default="Biz Bilan Bog'laning", max_length=200),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='button_text',
            field=models.CharField(default='Bepul Konsultatsiya', max_length=50),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='description',
            field=models.TextField(default='Biz sizning huquqlaringizni himoya qilamiz.'),
        ),
        migrations.AlterField(
            model_name='practicearea',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='practicearea',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='quote',
            field=models.TextField(verbose_name='Fikr matni'),
        ),
    ]
