"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import dj_database_url
from django.templatetags.static import static
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


import os
from dotenv import load_dotenv # <--- YANGI IMPORT

# .env faylni yuklaymiz
load_dotenv()
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG') == 'True'

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '.vercel.app',  # Hamma vercel bilan tugaydigan linklarga ruxsat beradi
    'firmayurist.uz', # Sening .uz domening uchun
]

# Application definition

INSTALLED_APPS = [
    "unfold",
    'cloudinary_storage',
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary',
    'django_ckeditor_5',
    "home",
    'blog',
    'dashboard',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('DATABASE_URL'),
        conn_max_age=600
    )
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/



# CKEditor 5 Sozlamalari
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': ['heading', '|', 'bold', 'italic', 'link',
                    'bulletedList', 'numberedList', 'blockQuote', 'imageUpload', 'insertTable', 'mediaEmbed', 'undo', 'redo'],
        'theme': 'default',
    },
    'extends': {
        'blockToolbar': [
            'paragraph', 'heading1', 'heading2', 'heading3',
            '|',
            'bulletedList', 'numberedList',
            '|',
            'blockQuote', 'imageUpload'
        ],
        'toolbar': ['heading', '|', 'outdent', 'indent', '|', 'bold', 'italic', 'link', 'underline', 'strikethrough',
                    'code','subscript', 'superscript', 'highlight', '|', 'insertImage',
                    'bulletedList', 'numberedList', 'todoList', '|',  'blockQuote', 'imageUpload', '|',
                    'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', 'mediaEmbed', 'removeFormat',
                    'insertTable',],
        'image': {
            'toolbar': ['imageTextAlternative', '|', 'imageStyle:alignLeft', 'imageStyle:alignRight', 'imageStyle:alignCenter', 'imageStyle:side',  '|'],
            'styles': [
                'full',
                'side',
                'alignLeft',
                'alignRight',
                'alignCenter',
            ]
        },
        'table': {
            'contentToolbar': [ 'tableColumn', 'tableRow', 'mergeTableCells', 'tableProperties', 'tableCellProperties' ],
        },
        'heading': {
            'options': [
                { 'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph' },
                { 'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1' },
                { 'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2' },
                { 'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3' }
            ]
        }
    }
}

# config/settings.py faylida:

# ...



# 1. BIZNING FAQSAT QO'SHGAN STATIK FAYLLARIMIZ (CSS, Images)
STATICFILES_DIRS = [
    BASE_DIR / "static",
]


MEDIA_ROOT = BASE_DIR / 'media'

# config/settings.py eng pastida:

UNFOLD = {
    "SITE_TITLE": "Shohjahon Abdurahimov",
    "SITE_HEADER": "Boshqaruv Paneli",
    "SITE_SYMBOL": "shield",  # Yuristga mos ikonka
    "SHOW_HISTORY": False,    # Tarix kerak emas
    "SITE_URL": "/",


    "SIDEBAR": {
        "show_search": False, # Qidiruvni o'chiramiz
        "show_all_applications": False, # <--- BU MUHIM! (Avtomatik ro'yxatni o'chiradi)

        "navigation": [
            {
                "title": "ASOSIY SAHIFA SOZLAMALARI",
                "separator": True, # Chiroyli chiziq tortadi
                "items": [
                    {
                        "title": "Hero (Tepa qism)",
                        "icon": "home",
                        "link": "/yurist-control-panel-v1/home/herosection/",
                    },
                    {
                        "title": "Biz haqimizda",
                        "icon": "person",
                        "link": "/yurist-control-panel-v1/home/aboutsection/",
                    },
                    {
                        "title": "Ishonch (Logolar)",
                        "icon": "verified", # Yoki 'stars'
                        # Agar Logolar uchun alohida model qilgan bo'lsang, o'shani ula
                        # "link": "/admin/home/trustedby/",
                    },
                ],
            },
            {
                "title": "XIZMATLAR VA ISHLAR",
                "separator": True,
                "items": [
                    {
                        "title": "Xizmatlar (Practice Areas)",
                        "icon": "gavel",
                        "link": "/yurist-control-panel-v1/home/practicearea/",
                    },
                    {
                        "title": "Bajarilgan Ishlar (Case Studies)",
                        "icon": "folder_open",
                        "link": "/yurist-control-panel-v1/home/casestudy/",
                    },
                    {
                        "title": "Mijozlar Fikri (Testimonials)",
                        "icon": "format_quote",
                        "link": "/yurist-control-panel-v1/home/testimonial/",
                    },
                ],
            },
            {
                "title": "ALOQA",
                "separator": True,
                "items": [
                    {
                        "title": "Kontakt va Futer",
                        "icon": "contact_phone",
                        "link": "/yurist-control-panel-v1/home/contactsettings/",
                    },
                ],
            },
             # Agar Blog Kategoriyalarini shu yerdan o'zgartirishini xohlasang:
            {
                "title": "BLOG SOZLAMALARI",
                "items": [
                    {
                        "title": "Kategoriyalar",
                        "icon": "category",
                        "link": "/yurist-control-panel-v1/blog/category/",
                    },
                ],
            },
        ],
    },
}

TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN')
TELEGRAM_CHAT_ID = os.getenv('TELEGRAM_CHAT_ID')

# Cloudinary Sozlamalari
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
}

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media (Rasmlar) Cloudinary ga ketadi
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
MEDIA_URL = '/media/'